### ISSUE TITLE
webpackMissingModule: Cannot find module "apollo-cache"

### ISSUE THREAD

**Issue by christophermlne** [ember-graphql/ember-apollo-client#333]
```
-apollo-client-bundle.js:73 Uncaught Error: Cannot find module "apollo-cache"
    at webpackMissingModule (-apollo-client-bundle.js:73)
    at Object.<anonymous> (-apollo-client-bundle.js:73)
    at __webpack_require__ (-apollo-client-bundle.js:20)
    at -apollo-client-bundle.js:66
    at Module.callback (-apollo-client-bundle.js:69)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
```

I've been stuck on this for quite a while (like, over a year), but it has now become critical.

I am using ember-apollo-client 1.0.5.

When I upgrade ember-source to 3.11 I start getting the error. In fact, if I upgrade certain other dependencies like simple-auth i start getting the error.

I was able to upgrade ember-source from 3.9.x to 3.10.x WITHOUT getting the error, but as soon as I move to 3.11.x the error starts happening.

Any ideas appreciated. Of course, if you know the answer, that's even more appreciated.

My package.json:

```
{
  "name": "<redacted>",
  "version": "0.0.0",
  "private": true,
  "description": "<redacted>",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember s -p 4300 --proxy=http://localhost:4000",
    "test": "ember test"
  },
  "devDependencies": {
    "ember-auto-import": "^1.5.3",
    "@ember/jquery": "^0.6.0",
    "@ember/optional-features": "^0.7.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-ajax": "^5.0.0",
    "ember-apollo-client": "^1.0.5",
    "ember-array-contains-helper": "^2.0.0",
    "ember-cli": "~3.11.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.7.3",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^3.0.1",
    "ember-cli-htmlbars-inline-precompile": "^2.1.0",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-tailwind": "^0.6.0",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-click-outside": "^1.0.0",
    "ember-concurrency": "^0.10.0",
    "ember-export-application-global": "^2.0.0",
    "ember-link-action": "^0.1.2",
    "ember-material-design-icons-shim": "^0.1.13",
    "ember-load-initializers": "^2.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-moment": "^7.7.0",
    "ember-page-title": "^5.0.1",
    "ember-qunit": "^4.4.1",
    "ember-resolver": "^5.0.1",
    "ember-simple-auth": "^1.8.0",
    "ember-source": "~3.10.0",
    "ember-sticky-element": "^0.2.3",
    "ember-test-selectors": "^1.0.0",
    "ember-truth-helpers": "^2.1.0",
    "ember-welcome-page": "^4.0.0",
    "eslint-plugin-ember": "^6.2.0",
    "eslint-plugin-node": "^9.0.1",
    "loader.js": "^4.7.0",
    "sass": "^1.20.1",
    "virtual-each": "^0.6.2",
    "qunit-dom": "^0.8.4"
  },
  "engines": {
    "node": "8.* || >= 10.*"
  },
  "dependencies": {
    "smoothscroll-polyfill": "^0.4.3"
  }
}
```

**Comment by josemarluedke** [comment]
Interesting this happens by upgrading ember-source.

It seems you are using version 1.0.5, which uses a custom webpack build to get apollo in your app. 

I would suggest upgrading to v2.0.0 where that custom webpack is not present anymore (we are now using ember-auto-import). 
Due to the number of breaking changes in v2, you can also upgrade to v2.0.0-beta.1 to see if it solves this particular issue. This beta version was the first version to change from the custom webpack setup to ember-auto-import.

Let me know how it goes.

**Comment by christophermlne** [comment]
@josemarluedke i just tried your suggestion.

i get a slightly different error now

```
loader.js:247 Uncaught Error: Could not find module `apollo-link-context` imported from `prototype/services/apollo`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:422)
    at Class.resolveOther (index.js:103)
    at Class.resolve (index.js:163)
    at resolve (container.js:1197)
    at Registry.resolve (container.js:737)
missingModule @ loader.js:247
findModule @ loader.js:258
Module.findDeps @ loader.js:168
findModule @ loader.js:262
requireModule @ loader.js:24
_extractDefaultExport @ index.js:422
resolveOther @ index.js:103
resolve @ index.js:163
resolve @ container.js:1197
resolve @ container.js:737
resolve @ container.js:740
has @ container.js:1214
has @ container.js:834
proto.validateInjections @ container.js:1142
create @ container.js:519
instantiateFactory @ container.js:359
lookup @ container.js:287
lookup @ container.js:131
lookup @ container_proxy.js:78
getRoute @ router.js:96
fetchRoute @ router_js.js:826
get route @ router_js.js:738
applyToState @ router_js.js:1346
getTransitionByIntent @ router_js.js:1490
transitionByIntent @ router_js.js:1445
doTransition @ router_js.js:1579
handleURL @ router_js.js:2041
_doURLTransition @ router.js:419
handleURL @ router.js:415
startRouting @ router.js:324
startRouting @ instance.js:148
didBecomeReady @ application.js:699
invoke @ backburner.js:335
flush @ backburner.js:226
flush @ backburner.js:423
_end @ backburner.js:957
end @ backburner.js:707
_run @ backburner.js:1012
_join @ backburner.js:986
join @ backburner.js:757
join @ index.js:165
(anonymous) @ index.js:260
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
jQuery.readyException @ jquery.js:3849
(anonymous) @ jquery.js:3869
mightThrow @ jquery.js:3557
process @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
process @ jquery.js:3645
setTimeout (async)
(anonymous) @ jquery.js:3663
fire @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
fire @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
completed @ jquery.js:3911
Show 14 more frames
```

**Comment by christophermlne** [comment]
hold the phone.
i think that actually worked after i explicitly added `apollo-link-context` to my dependencies

**Comment by christophermlne** [comment]
my issue is resolved thank you @josemarluedke
